services:
  web-hzsi:
    env_file:
      - compose.env
    image: $IMAGE
    command: sudo /usr/bin/supervisord -nc /etc/supervisord.conf
    container_name: hzsi-web
    hostname: hzsi-web
    tty: true
    stdin_open: true
    user: root
    ports:
      - "80:80"
      - "443:443"
      - "8001:8001"
      - "3001:3001"
      - "6899:6899"
    depends_on:
      - db-hzsi
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - $HOME:/mnt
      - $HOME/.docker_zsh_history:/home/user/.zsh_history
      - /dev/log:/dev/log
      - /etc/localtime:/etc/localtime:ro
      - ../:/home/user/hrzoosignup-source
      - ../bin/hzsi-db:$VENV/bin/hzsi-db
      - ../bin/hzsi-genseckey:$VENV/bin/hzsi-genseckey
      - ../bin/hzsi-manage:$VENV/bin/hzsi-manage
      - ../bin/hzsi-users:$VENV/bin/hzsi-users
      - ../bin/hzsi-projects:$VENV/bin/hzsi-projects
      - ./collectstatic.sh:/home/user/collectstatic.sh
      - ./pysitepkg:/home/user/pysitepkg
      - ./run-django-server.sh:/home/user/run-django-server.sh
      - ./run-frontdev-server.sh:/home/user/run-frontdev-server.sh
      - ./syncsite.sh:/home/user/syncsite.sh
      - ./memcache.ini:/etc/supervisord.d/memcache.ini
      - ../etc/:$VENV/etc/hrzoosignup
      - ../hrzoosignup/:$VENV/lib/python3.9/site-packages/hrzoosignup
      - ../hrzoosignup/frontend/:/home/user/frontend
      - ../hrzoosignup/static/:$VENV/share/hrzoosignup/static
    networks:
      hzsi-front-app_net:
        ipv4_address: 172.20.0.12
  db-hzsi:
    env_file:
      - compose.env
    container_name: hzsi-postgres15
    image: postgres:15
    volumes:
      - $PSQLDATA:/var/lib/postgresql/data
    networks:
      hzsi-front-app_net:
        ipv4_address: 172.20.0.13

networks:
  hzsi-front-app_net:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
