# Generated by Django 4.2 on 2023-04-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='croris_id',
            field=models.PositiveBigIntegerField(null=True, verbose_name='CroRIS id'),
        ),
    ]
