# Generated by Django 4.2 on 2023-04-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, max_length=24, verbose_name='Role name'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(blank=True, max_length=24, verbose_name='Project state'),
        ),
        migrations.AlterField(
            model_name='user',
            name='person_affiliation',
            field=models.CharField(blank=True, max_length=64, verbose_name='Affiliation - LDAP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='person_institution',
            field=models.CharField(blank=True, max_length=128, verbose_name='Institution - LDAP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='person_mail',
            field=models.EmailField(blank=True, max_length=64, verbose_name='Email - LDAP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='person_uniqueid',
            field=models.CharField(blank=True, max_length=128, verbose_name='hrEduPersonUniqueID - LDAP'),
        ),
    ]
