# Generated by Django 4.2 on 2023-04-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial_squashed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sshpublickey',
            unique_together={('name', 'user', 'fingerprint')},
        ),
        migrations.AddField(
            model_name='sshpublickey',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
