# Generated by Django 4.1.7 on 2023-04-04 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('reason', models.CharField(max_length=1024, verbose_name='reason')),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=128, verbose_name='Approved by')),
                ('denied_by', models.CharField(blank=True, max_length=128, verbose_name='Approved by')),
                ('science_field', models.JSONField(blank=True, null=True)),
                ('science_software', models.JSONField(blank=True, null=True)),
                ('science_extrasoftware', models.CharField(blank=True, max_length=256, null=True, verbose_name='Extra software needed on project')),
                ('science_extrasoftware_help', models.BooleanField()),
                ('resources_numbers', models.JSONField(blank=True, null=True)),
                ('resources_type', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('date_extensions', models.DateField(blank=True, null=True)),
                ('croris_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='CroRIS title')),
                ('croris_start', models.DateField(blank=True, null=True)),
                ('croris_end', models.DateField(blank=True, null=True)),
                ('croris_identifier', models.CharField(blank=True, max_length=48, null=True, verbose_name='CroRIS hrSifraProjekta')),
                ('croris_id', models.PositiveBigIntegerField(verbose_name='CroRIS id')),
                ('croris_summary', models.CharField(blank=True, max_length=512, null=True, verbose_name='CroRIS summary')),
                ('croris_collaborators', models.JSONField(blank=True, null=True, verbose_name='CroRIS osobeResources -voditelj')),
                ('croris_lead', models.JSONField(blank=True, null=True, verbose_name='CroRIS osobeResources voditelj')),
                ('croris_finance', models.JSONField(blank=True, max_length=256, null=True, verbose_name='CroRIS financijeri entityNameHr')),
                ('croris_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='CroRIS tipProjekta')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=24, null=True, verbose_name='Role name')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=24, null=True, verbose_name='Project state')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='aaieduhr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='croris_first_name',
            field=models.CharField(blank=True, max_length=48, verbose_name='CroRIS first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='croris_last_name',
            field=models.CharField(blank=True, max_length=48, verbose_name='CroRIS last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='person_affiliation',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Affiliation'),
        ),
        migrations.AddField(
            model_name='user',
            name='person_institution',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='user',
            name='person_uniqueid',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='hrEduPersonUniqueID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='CroRIS email address'),
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.project')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='states',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.state'),
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(through='backend.UserProject', to=settings.AUTH_USER_MODEL),
        ),
    ]
