# Generated by Django 4.2 on 2023-04-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_project_croris_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='staff_resources_type',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='reason',
            field=models.CharField(max_length=4096, verbose_name='reason'),
        ),
        migrations.CreateModel(
            name='StaffComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, null=True, verbose_name='Staff comment on managing request')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Datetime when comment is added')),
                ('comment_by', models.JSONField(blank=True, null=True, verbose_name='JSONField with few details of staff that made comment')),
                ('name', models.CharField(blank=True, max_length=24, verbose_name='Project state when the comment was made')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.project')),
            ],
        ),
    ]
