# Generated by Django 4.1.7 on 2023-04-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_initial_user_project_role_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='croris_mail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='CroRIS email address'),
        ),
        migrations.AddField(
            model_name='user',
            name='person_mail',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Email - LDAP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='person_affiliation',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Affiliation - LDAP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='person_institution',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Institution - LDAP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='person_uniqueid',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='hrEduPersonUniqueID - LDAP'),
        ),
    ]
