# Generated by Django 4.2 on 2023-04-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_role_name_alter_state_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(null=True)),
            ],
        ),
    ]
