# Generated by Django 4.2 on 2023-04-10 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_projectcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='identifier',
            field=models.CharField(default=datetime.datetime(2023, 4, 10, 17, 38, 17, 594352, tzinfo=datetime.timezone.utc), max_length=32, unique=True, verbose_name='identifier'),
            preserve_default=False,
        ),
    ]
