# Generated by Django 4.2 on 2023-04-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_sshpublickey_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=24, verbose_name='modulefile or concrete software name')),
            ],
        ),
    ]
