# Generated by Django 4.1.7 on 2023-04-04 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_croris_mail_user_person_mail_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='croris_identifier',
            field=models.CharField(blank=True, default='', max_length=48, verbose_name='CroRIS hrSifraProjekta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='croris_summary',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='CroRIS summary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='croris_title',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='CroRIS title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='croris_type',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='CroRIS tipProjekta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='science_extrasoftware',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Extra software needed on project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='Role name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='Project state'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='person_affiliation',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Affiliation - LDAP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='person_institution',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Institution - LDAP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='person_mail',
            field=models.EmailField(blank=True, default='', max_length=64, verbose_name='Email - LDAP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='person_uniqueid',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='hrEduPersonUniqueID - LDAP'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SSHPublicKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('fingerprint', models.CharField(max_length=47)),
                ('public_key', models.TextField(max_length=2000)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
