# Generated by Django 4.2 on 2023-04-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_project_croris_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='person_oib',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='OIB number - LDAP'),
        ),
        migrations.AddField(
            model_name='user',
            name='person_organisation',
            field=models.CharField(blank=True, max_length=128, verbose_name='Organisation unit - LDAP'),
        ),
    ]
