# Generated by Django 4.2 on 2023-04-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_dateextend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffcomment',
            old_name='name',
            new_name='project_state',
        ),
        migrations.AlterField(
            model_name='staffcomment',
            name='comment',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Staff comment on managing request'),
        ),
    ]
