# Generated by Django 4.2 on 2023-04-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_name_staffcomment_project_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_approved',
            new_name='date_changed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date_extensions',
        ),
    ]
