# Generated by Django 4.2 on 2023-07-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_project_croris_end_alter_project_croris_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sciencesoftware',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datetime when application is added'),
        ),
    ]
