# Generated by Django 4.2 on 2023-04-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_user_person_oib_user_person_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='person_oib',
            field=models.CharField(blank=True, max_length=11, verbose_name='OIB number - LDAP'),
        ),
    ]
