# Generated by Django 4.2 on 2023-04-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_user_person_oib'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sshpublickey',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='sshpublickey',
            unique_together={('name', 'user')},
        ),
    ]
