# Generated by Django 4.2 on 2023-07-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_sciencesoftware_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='sciencesoftware',
            name='added_by',
            field=models.JSONField(blank=True, null=True, verbose_name='JSONField with few details of staff that added application'),
        ),
    ]
