# Generated by Django 4.2 on 2023-04-15 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_custominvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custominvitation',
            name='emails',
        ),
    ]
