# Generated by Django 4.2 on 2023-04-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_custominvitation_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='approved_by',
            field=models.JSONField(blank=True, null=True, verbose_name='JSONField with few details of staff that approved request'),
        ),
        migrations.AlterField(
            model_name='project',
            name='denied_by',
            field=models.JSONField(blank=True, null=True, verbose_name='JSONField with few details of staff that denied request'),
        ),
    ]
