# Generated by Django 4.2.3 on 2023-11-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_project_change_history_project_changed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
