# Generated by Django 4.2 on 2023-04-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_projecttype_remove_project_states_project_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='croris_summary',
            field=models.CharField(blank=True, max_length=8192, verbose_name='CroRIS summary'),
        ),
    ]
