# Generated by Django 4.2 on 2023-04-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_project_croris_institute_project_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominvitation',
            name='person_oib',
            field=models.CharField(blank=True, max_length=11, verbose_name='OIB number'),
        ),
    ]
