# Generated by Django 4.2 on 2023-04-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_project_croris_end_alter_project_croris_start_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userproject',
            unique_together={('user', 'project')},
        ),
    ]
