# Generated by Django 4.2.3 on 2023-11-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='croris_mbz',
            field=models.CharField(blank=True, max_length=10, verbose_name='CroRIS MBZ number'),
        ),
    ]
