# Generated by Django 4.2 on 2023-04-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_custominvitation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominvitation',
            name='person_oib',
            field=models.CharField(blank=True, max_length=11, verbose_name='OIB number'),
        ),
    ]
