# Generated by Django 4.2.3 on 2023-11-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_user_croris_mbz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='croris_mbz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CroRIS MBZ number'),
        ),
    ]
