# Generated by Django 4.2.3 on 2023-11-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_set_project_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(blank=True, help_text='Custom is_active field that will designate whether user is assigned to active HRZOO project', verbose_name='custom_active'),
        ),
    ]
