# Generated by Django 4.2.3 on 2023-12-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mailinglist_subscribe',
            field=models.BooleanField(blank=True, default=False, help_text='Boolean field that indicates whether user is subscribed to mailinglist', verbose_name='mailinglist_subscribe'),
            preserve_default=False,
        ),
    ]
