# Generated by Django 4.2.3 on 2024-01-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_user_mailinglist_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrorisInstitutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, verbose_name='Institution exist in the register')),
                ('name_long', models.CharField(blank=True, max_length=512, verbose_name='Long name of institution')),
                ('name_short', models.CharField(blank=True, max_length=256, verbose_name='Short name of institution')),
                ('name_acronym', models.CharField(blank=True, max_length=256, verbose_name='Acronym of institution')),
                ('oib', models.CharField(blank=True, max_length=11, verbose_name='OIB number')),
                ('mbs', models.CharField(blank=True, max_length=9, verbose_name='MBS number')),
                ('mbu', models.CharField(blank=True, max_length=3, verbose_name='MBU number')),
                ('contact_web', models.CharField(blank=True, max_length=256, verbose_name='Web URL of institution')),
                ('contact_email', models.CharField(blank=True, max_length=128, verbose_name='Main email contact of institution')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='person_institution_oib',
            field=models.CharField(blank=True, max_length=11, verbose_name='Institution OIB number'),
        ),
        migrations.AddField(
            model_name='user',
            name='person_username',
            field=models.CharField(blank=True, max_length=10, verbose_name='Username - LDAP'),
        ),
        migrations.AlterField(
            model_name='project',
            name='croris_institute',
            field=models.JSONField(blank=True, max_length=512, null=True, verbose_name='CroRIS institute'),
        ),
    ]
