# Generated by Django 4.2.3 on 2024-01-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_set_user_mailinglist_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='person_username',
            field=models.CharField(blank=True, max_length=8, verbose_name='Username - LDAP'),
        ),
    ]
