# Generated by Django 4.2.9 on 2024-01-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_custominvitation_inviter'),
        ('backend', '0017_crorisinstitutions_user_person_institution_oib_and_more'),
    ]

    operations = [
    ]
