# Generated by Django 4.2.3 on 2024-01-31 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_merge_20240130_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='person_institution_realm',
            field=models.CharField(blank=True, max_length=64, verbose_name='Institution realm - hrEduPersonHomeOrg'),
        ),
        migrations.AlterField(
            model_name='custominvitation',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
