# Generated by Django 4.2.3 on 2024-01-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_user_person_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrorisInstitutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, verbose_name='Institution exist in the register')),
                ('name_long', models.CharField(blank=True, max_length=512, verbose_name='Long name of institution')),
                ('name_short', models.CharField(blank=True, max_length=256, verbose_name='Short name of institution')),
                ('name_acronym', models.CharField(blank=True, max_length=32, verbose_name='Acronym of institution')),
                ('oib', models.CharField(blank=True, max_length=11, verbose_name='OIB number')),
                ('mbs', models.CharField(blank=True, max_length=9, verbose_name='MBS number')),
                ('mbu', models.CharField(blank=True, max_length=3, verbose_name='MBU number')),
                ('contact_web', models.CharField(blank=True, max_length=256, verbose_name='Web URL of institution')),
                ('contact_email', models.CharField(blank=True, max_length=128, verbose_name='Main email contact of institution')),
            ],
        ),
    ]
