# Generated by Django 4.2.3 on 2024-01-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_crorisinstitutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crorisinstitutions',
            name='name_acronym',
            field=models.CharField(blank=True, max_length=256, verbose_name='Acronym of institution'),
        ),
    ]
