# Generated by Django 4.2.11 on 2024-05-31 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_user_person_institution_manual_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominvitation',
            name='invtype',
            field=models.CharField(blank=True, max_length=16, verbose_name='Invitation type'),
        ),
        migrations.AddField(
            model_name='user',
            name='person_type',
            field=models.CharField(blank=True, max_length=32, verbose_name='Local, Foreigner'),
        ),
        migrations.AlterField(
            model_name='custominvitation',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='inviter'),
        ),
    ]
