# Generated by Django 4.2.3 on 2024-01-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_crorisinstitutions_name_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='person_institution_oib',
            field=models.CharField(blank=True, max_length=11, verbose_name='Institution OIB number'),
        ),
    ]
