# Generated by Django 4.2.11 on 2024-07-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_resourceusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceusage',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
