# Generated by Django 4.2.17 on 2025-01-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_resourceusage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bogus_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
