# Generated by Django 4.2.17 on 2025-01-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_project_bogus_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='crorisinstitutions',
            name='parent',
            field=models.CharField(blank=True, max_length=512, verbose_name='Long name of parent institution'),
        ),
    ]
