# Generated by Django 4.2.21 on 2025-05-16 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_organization4apikey_myapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExtend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Datetime when comment is added')),
                ('approved', models.BooleanField()),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='New date_end of project')),
                ('reason', models.CharField(max_length=4096, verbose_name='reason')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.project')),
            ],
        ),
        migrations.DeleteModel(
            name='DateExtend',
        ),
    ]
