# Generated by Django 4.2.21 on 2025-05-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_projectextend_delete_dateextend'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectextend',
            name='approved_by',
            field=models.JSONField(blank=True, null=True, verbose_name='JSONField with few details of staff that approved request'),
        ),
        migrations.AddField(
            model_name='projectextend',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectextend',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datetime when extension request is submitted'),
        ),
        migrations.AlterField(
            model_name='projectextend',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='New date_end of project'),
        ),
    ]
