# Generated by Django 4.2.21 on 2025-05-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_projectextend_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crorisinstitutions',
            name='mbs',
            field=models.CharField(blank=True, max_length=12, verbose_name='MBS number'),
        ),
    ]
