# Generated by Django 4.2.27 on 2026-01-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_alter_crorisinstitutions_mbs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScienceSoftware',
        ),
        migrations.RemoveField(
            model_name='project',
            name='science_extrasoftware',
        ),
        migrations.RemoveField(
            model_name='project',
            name='science_extrasoftware_help',
        ),
        migrations.RemoveField(
            model_name='project',
            name='science_software',
        ),
    ]
