# Generated by Django 4.2.27 on 2026-01-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_delete_sciencesoftware_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uses_ai_tech',
            field=models.CharField(choices=[('yes', 'Uses AI technologies'), ('no', 'Does not use AI technologies'), ('undeclared', 'Not declared yet')], default='undeclared', max_length=10),
        ),
    ]
