# Generated by Django 4.2.27 on 2026-01-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_setflag_uses_ai_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='uses_ai_tech',
            field=models.BooleanField(default=False),
        ),
    ]
